### ISSUE TITLE
tiny mce inside a fluentui dialog - the menus do not open

### ISSUE THREAD

**Issue by ishaisagi** [tinymce/tinymce-react#270]
using  Dialog (from "@fluentui/react") and adding a tinymce to the dialog, the control works well with one exception - the menus (edit\insert\view\format etc) are not opening when clicked.

exact same tinymce code but inside a materialui dialog works well...but my application needs to use fluent.
any advice?

**Comment by ishaisagi** [comment]
ok, I found that I have to add:
$(".tox-tinymce-aux").css("z-index","1900000")
to the "onLayerDidMount" event of the dialog.

**Comment by anton-johansson** [comment]
I'm having the same issue in a Charka UI dialog.

**Comment by tiny-james** [comment]
Here is an example:
https://codesandbox.io/s/tinymce-react-fluentui-modal-cgzkq

Two things were needed:

1. The z-index of the popups and menus need to be increased.
```css
body.tox-fullscreen .tox.tox-tinymce.tox-fullscreen {
  z-index: 1000001;
}

.tox.tox-silver-sink.tox-tinymce-aux {
  z-index: 1000001;
}
```
2.  `forceFocusInsideTrap` had to be turned off on the modal.
